### ISSUE TITLE
Macro for iOS6

### ISSUE THREAD

**Issue by winkelsdorf** [croberts22/CRNavigationController#8]
Version check should include iOS6 for backwards compatibility. I just tried to install it via CocoaPods and it fails, as the min. requirement is iOS7.

Obviously there are still apps which need to support iOS6 and iOS7. This class could act as a wrapper without functionality when running on anything < iOS7.

Opinions?

**Comment by croberts22** [comment]
As far as CocoaPods is concerned, I haven't really kept that up-to-date. I've been meaning to but I've been swamped with external work as of late.

I've also considered this and will probably add this into a minor release.

Just to let you know though, the readme does explicitly state iOS 7 for now. If you need to have functionality for iOS 6 immediately, I'd suggest you create your own wrapper for now until I can push an update. It wouldn't be too hard. ;)

**Comment by winkelsdorf** [comment]
Sure, that's what I am going to do. It was meant more like a feature request to prevent others running into that.

On thing about the CocoaPods: The showstopper is that you must specify the iOS Platform in a project podspec. iOS7 is required to even start fetching and integrating the CRNavigationController pod. This in turn prevents the dylib created to be running in a project targeting and executed on iOS6..

Manually integrating this little time saver component now with a wrapper is more a finger exercise ;)

Thanks for your work, great to see other Pixel Perfect Coders taking care of those things too!

**Comment by croberts22** [comment]
I think the biggest issue is the API differences between iOS 6 and 7...specifically, `tintColor` and `barTintColor` respectively. I'd like to respect those APIs and would rather keep them separated instead of trying to group them into a single method. Since `UINavigationController` in iOS 7 also has `tintColor`, I wouldn't want to necessarily override that method in case someone needed to use that. 

You would still be able to use CRNavigationController, but you would just have to add a condition to check if the version is 7 or earlier, as such:

```
    if(SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(@"7.0"))
        self.navigationController.navigationBar.barTintColor = tintColor;
    else
        self.navigationController.navigationBar.tintColor = tintColor;
```

Alternatively, a different method within the navigation controller (say, `setColor`) could exist that has this logic.

**Comment by winkelsdorf** [comment]
Thanks for the follow-up on this, but I think we talk past each other.

Imagine the following situation: Somebody needs to maintain code in Xcode 5 (= iOS7 SDK). The code should be executable under iOS6 and iOS7.

Using CRNavigationController via CocoaPods fails, because this project's pod _requires_ iOS7. There are still a lot of project targeting the current and the previous version of iOS at the same time, as far as I know it's best practice to support one version before the current available major version.

Your source should work fine under iOS6 as you are using a descendant of setBarTintColor and there is no system call from a parent to this one under iOS6.

The only problem might be the call to super - but then again, it should work as the method isn't executed at all.

By the way, I think it's better to check if a feature is available instead of checking the OS version, something like:

``` objc
if ([self respondsToSelector:@selector(barTintColor)]) {
        self.barTintColor = [UIColor someColor];
    }
```

But again, this should not be needed at all, as there is no call to setBarTintColor under iOS6.

Supporting SDK for iOS6 is a totally different topic, this would likely break due to missing declaration of BarTintColor. But here we are safe as we are always linking against SDK 7 but runtime might be using iOS6 (and SDK 6.0/6.1).

Long story, short: Just update the pod and it should work out of the box.

**Comment by croberts22** [comment]
Ah, gotcha. I was a bit wrapped up with the backwards compatibility and missed the CocoaPods discussion. Yeah, like I mentioned before, I did a pretty amateur job with the pods stuff and most likely got caught up with other things before making it right. That's why you'll notice the version (I think) is still set to 0.0.1. I've already created a ticket to update this.

There is no `setBarTintColor` in iOS 6 of course, but compiling with the 7.0 SDK as you mentioned can compile successfully, but generate runtime exceptions when running an iOS 6-based device. That was where most of my discussion was coming from.

**Comment by winkelsdorf** [comment]
That's what I thought when I read your reply ;)

Yes, sure - it's not an urgent issue at all, and it can still be used in the way we described here (including the source without CocoaPods). So anybody else wondering can look up our discussion.

Cheers,
Frederik

**Comment by croberts22** [comment]
Duly noted! Thanks. :)
